"""The MANIFEST.md answer key, as a machine-readable registry.

MANIFEST.md is written for people. Consumers such as SWIZZLE and Warden need
the same answers as data: which file, what class of specimen, what verdict a
working verifier must reach. This module is that translation.

There are four copies of each answer, and they are all checked against each
other every time `verify_manifest.py` runs:

1. the human prose in MANIFEST.md (checked by a short "prose marker" per
   specimen: a phrase that must appear in the right row or section);
2. the machine block at the end of MANIFEST.md (generated, never hand-edited);
3. the table `MANIFEST_SPECIMENS` below (the source the block is built from);
4. `registry.json`, which consumers read (generated, never hand-edited).

Any disagreement, in any direction, fails verification. Changing an answer
therefore takes a deliberate, reviewable act: edit the prose and the table,
then run the explicit write command, which refuses to run unless the
corpus still behaves as the claims say.

    python3 -m assay_production.manifest_registry          # print registry.json
    python3 -m assay_production.manifest_registry --write  # re-record everything

`--write` is the only thing that records content hashes. A specimen edit is a
change to the answer key and must be reviewed like one.

Only specimens whose files exist are registered. `cns_specimens.py` describes
a CNS-readiness catalogue whose files (`specimens/cns/`) have not been built;
those are deliberately absent so no consumer is handed a path to nothing.
"""
from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from .specimen_registry import DuplicateSpecimenId, SpecimenRecord, SpecimenRegistry

ROOT = Path(__file__).resolve().parent.parent
REGISTRY_PATH = Path(__file__).resolve().parent / "registry.json"

BLOCK_BEGIN = "<!-- ASSAY-MACHINE-BLOCK:BEGIN (generated by `python3 -m assay_production.manifest_registry --write`; do not edit by hand) -->"
BLOCK_END = "<!-- ASSAY-MACHINE-BLOCK:END -->"
_BLOCK_BEGIN_RE = re.compile(r"<!-- ASSAY-MACHINE-BLOCK:BEGIN[^>]*-->")
BLOCK_FORMAT = 1

P = "specimens/pairs/"
R = "specimens/reference/"
S = "specimens/superseded/"
U = "specimens/progressions/uztc/"


def _row(find: str, *says: str) -> dict:
    """The prose marker for a verdict stated in a table row of MANIFEST.md."""
    return {"unit": "row", "find": find, "says": list(says)}


def _section(find: str, *says: str) -> dict:
    """The prose marker for a verdict stated in a heading's section of MANIFEST.md."""
    return {"unit": "section", "find": find, "says": list(says)}


# (id, class, primary path, companion paths, expected verdict, failure mode,
#  manifest section, what it is, prose marker)
MANIFEST_SPECIMENS: List[dict] = [
    # --- 1. Reconstruction pairs ------------------------------------------
    dict(id="pair_governance_os_security", cls="RECONSTRUCTION_PAIR",
         path=P + "governance_os_security_source.py",
         companions=[P + "governance_os_security_adapter.py"],
         verdict="FAITHFUL", failure_mode=None, section="1",
         what="Flattened source and its reconstruction; 7 of 13 debris classes covered after normalisation.",
         prose=_row("| `governance_os_security_source.py` |", "**Faithful")),
    dict(id="pair_quorum_state_governance", cls="RECONSTRUCTION_PAIR",
         path=P + "quorum_state_governance_source.py",
         companions=[P + "quorum_state_governance_adapter.py"],
         verdict="CONSOLIDATED_LOSSY", failure_mode="lossy_reconstruction", section="1",
         what="Re-architecture into *Module classes; 2 of 7 debris classes covered.",
         prose=_row("| `quorum_state_governance_source.py` |", "**CONSOLIDATED / LOSSY")),
    dict(id="pair_solvar_stability_governance", cls="RECONSTRUCTION_PAIR",
         path=P + "solvar_stability_governance_source.py",
         companions=[P + "solvar_stability_governance_cleanup.py"],
         verdict="FAITHFUL", failure_mode=None, section="1",
         what="Paired with _cleanup: 31 of 32 debris classes covered.",
         prose=_row("| `solvar_stability_governance_source.py` |", "**FAITHFUL")),
    dict(id="pair_solvar_stability_consolidation", cls="RECONSTRUCTION_PAIR",
         path=P + "solvar_stability_governance_source.py",
         companions=[P + "solvar_stability_governance_adapter.py"],
         verdict="CONSOLIDATION_OF_SAME_SOURCE", failure_mode="lossy_reconstruction", section="1",
         what="Second, lossier reconstruction of the same source: 3 of 32 debris classes covered.",
         prose=_row("| `solvar_stability_governance_source.py` |",
                    "genuine *consolidation* of the same material")),
    dict(id="pair_sre_system_resilience", cls="RECONSTRUCTION_PAIR",
         path=P + "sre-system-resilience-evaluator-flattened.py",
         companions=[P + "sre_system_resilience_evaluator_adapter.py"],
         verdict="FAITHFUL", failure_mode=None, section="1",
         what="11 of 11 debris classes covered; thresholds made configurable.",
         prose=_row("| `sre-system-resilience-evaluator-flattened.py` |", "**FAITHFUL")),
    dict(id="pair_vanguard_behavioral_simulation", cls="RECONSTRUCTION_PAIR",
         path=P + "vanguard-behavioral-simulation-flattened.py",
         companions=[P + "vanguard-behavioral-simulation.py"],
         verdict="FAITHFUL", failure_mode=None, section="1",
         what="5 of 6 covered; the miss is a deliberate, documented rename.",
         prose=_row("| `vanguard-behavioral-simulation-flattened.py` |", "**FAITHFUL")),
    # --- 2. Version progression -------------------------------------------
    dict(id="uztc_progression", cls="VERSION_PROGRESSION",
         path=U + "uztc-construct-v1.2-validated.py",
         companions=[U + "uztc-construct-v1.0-flattened.py", U + "uztc-construct-v1.1-purged.py"],
         verdict="NOT_MONOTONIC_IMPROVEMENT", failure_mode="false_progression", section="2",
         what="Looks better at every step by parses/imports; the endpoint is the least functional.",
         prose=_section("## 2.", "A progression that looks monotonically better and is not is exactly what "
                                 "this specimen is for")),
    # --- 3. Failure modes -------------------------------------------------
    dict(id="fm_3_1_silent_pass", cls="FAILURE_MODE",
         path=P + "governance_os_security_source.py", companions=[],
         verdict="REFUSE", failure_mode="silent_pass", section="3.1",
         what="Whole file is one comment: imports cleanly, defines zero names.",
         prose=_section("### 3.1", "**REFUSE.**")),
    dict(id="fm_3_2_overclaim", cls="FAILURE_MODE",
         path=U + "uztc-construct-v1.2-validated.py", companions=[],
         verdict="CLAIM_FALSE", failure_mode="overclaim", section="3.2",
         what="Described as a 7-layer construct; its only method raises AttributeError.",
         prose=_section("### 3.2", "the documentation claim is **false**")),
    dict(id="fm_3_3_flattening_duplicate", cls="FAILURE_MODE",
         path=R + "wrapper/artifact_3.py", companions=[R + "secure/artifact_1.py"],
         verdict="SAME_CONTENT", failure_mode="flattening_duplicate", section="3.3",
         what="Same content twice, one flattened; wrapper/artifact_3.py is canonical.",
         prose=_section("### 3.3", "**the same content.**")),
    dict(id="fm_3_4_unreachable_branch", cls="FAILURE_MODE",
         path=P + "sre_system_resilience_evaluator_adapter.py", companions=[],
         verdict="UNREACHABLE", failure_mode="unreachable_branch", section="3.4",
         what="EvaluationVerdict.CRITICAL cannot be reached through evaluate_system_telemetry().",
         prose=_section("### 3.4", "the verdict is unreachable")),
    dict(id="fm_3_5_reskinned_duplicate", cls="FAILURE_MODE",
         path=P + "solvar_stability_governance_adapter.py",
         companions=[P + "sre_system_resilience_evaluator_adapter.py"],
         verdict="SAME_DESIGN_RESKINNED", failure_mode="reskinned_duplicate", section="3.5",
         what="Identical energy formula and thresholds under different class names.",
         prose=_section("### 3.5", "**the same design, reskinned")),
]

# --- 4. Superseded: negative examples --------------------------------------
# Only the files MANIFEST.md section 4 names. vanguard-unified-governance-
# wrapper.py is documented in specimens/superseded/ARCHIVE_README.md, not in
# MANIFEST.md, so it is left out until MANIFEST.md records an answer for it.
for _name, _says in [("sovereign-governance-stack-v1.py", "sovereign-governance-stack"),
                     ("sovereign-governance-stack-v2-expanded.py", "sovereign-governance-stack"),
                     ("unified-sovereign-kernel-wrapper.py", "unified-sovereign-kernel-wrapper"),
                     ("citadel-processor-router-flattened.py", "citadel-processor-router-flattened.py"),
                     ("resilience-config-dataclass.py", "resilience-config-dataclass.py"),
                     ("ure-universal-resilience-engine-flattened.py",
                      "ure-universal-resilience-engine-flattened.py")]:
    MANIFEST_SPECIMENS.append(dict(
        id="superseded_" + _name[:-3].replace("-", "_"), cls="SUPERSEDED",
        path=S + _name, companions=[], verdict="NOT_BEST_AVAILABLE",
        failure_mode="superseded", section="4",
        what="Tried and replaced; a verifier picking the best implementation must not choose this.",
        prose=_section("## 4.", "these are negative examples", _says)))

# --- 5. Reference implementations: must be accepted ------------------------
for _rel in ["sovereign_kernel.py", "secure/artifact_2.py", "code-repo-governance-and-gsa-core.py",
             "resilience_stability_kernel.py", "citadel_v1.2.py", "agent-factory-tactical-agents.py"]:
    MANIFEST_SPECIMENS.append(dict(
        id="reference_" + _rel[:-3].replace("/", "_").replace("-", "_").replace(".", "_"),
        cls="REFERENCE", path=R + _rel, companions=[], verdict="ACCEPT",
        failure_mode=None, section="5",
        what="Genuinely runs; refusing it is a false refusal.",
        prose=_section("## 5.", "must be **accepted**", _rel)))
MANIFEST_SPECIMENS.append(dict(
    id="reference_solvar_stability_governance_cleanup", cls="REFERENCE",
    path=P + "solvar_stability_governance_cleanup.py", companions=[], verdict="ACCEPT",
    failure_mode=None, section="5",
    what="Genuinely runs (needs matplotlib); refusing it is a false refusal.",
    prose=_section("## 5.", "must be **accepted**", "solvar_stability_governance_cleanup.py")))

_REQUIRED_KEYS = ("id", "cls", "path", "companions", "verdict", "failure_mode", "section", "what", "prose")


# --- table checks ----------------------------------------------------------

def table_problems(specs: Optional[List[dict]] = None) -> List[str]:
    """Plain-language problems with the table itself. Empty means it is sound."""
    specs = MANIFEST_SPECIMENS if specs is None else specs
    problems: List[str] = []
    seen: Dict[str, int] = {}
    for n, spec in enumerate(specs, 1):
        missing = [k for k in _REQUIRED_KEYS if k not in spec]
        if missing:
            problems.append(f"table row {n} ({spec.get('id', '?')}) lacks {', '.join(missing)}")
        sid = spec.get("id")
        if sid in seen:
            problems.append(f"duplicate specimen id {sid!r} (rows {seen[sid]} and {n}); "
                            "the later row would silently replace the earlier one")
        else:
            seen[sid] = n
    return problems


def check_table(specs: Optional[List[dict]] = None) -> None:
    problems = table_problems(specs)
    if problems:
        if any("duplicate" in p for p in problems):
            raise DuplicateSpecimenId("; ".join(problems))
        raise ValueError("; ".join(problems))


# --- hashing ---------------------------------------------------------------

def is_bytecode(parts: Tuple[str, ...]) -> bool:
    """True for a bytecode cache entry. They are hashed like any other file and are never expected."""
    return "__pycache__" in parts or parts[-1].endswith((".pyc", ".pyo"))


def _entries(base: Path):
    """Every entry under a directory as (relative parts, kind, path); links are never followed.

    kind is "file", "link" (a symbolic link, to a file or a folder) or "special"
    (a device, pipe or socket). Folders themselves are not listed.
    """
    import os
    for cur, dirs, files in os.walk(base, followlinks=False):
        for name in sorted(dirs):
            full = os.path.join(cur, name)
            if os.path.islink(full):
                yield Path(full).relative_to(base).parts, "link", Path(full)
        dirs[:] = sorted(d for d in dirs if not os.path.islink(os.path.join(cur, d)))
        for name in sorted(files):
            full = Path(cur) / name
            rel = full.relative_to(base).parts
            if full.is_symlink():
                yield rel, "link", full
            elif full.is_file():
                yield rel, "file", full
            else:
                yield rel, "special", full


def _entry_hash(kind: str, path: Path) -> str:
    """A file's SHA-256, or a marker no file can have for a link or special file."""
    import os
    if kind == "file":
        return hashlib.sha256(path.read_bytes()).hexdigest()
    if kind == "link":
        return "symlink->" + os.readlink(path)
    return "special-file"


def hash_path(root: Path, rel: str) -> Optional[str]:
    """SHA-256 of a file's raw bytes, or of a whole directory tree.

    Raw bytes on purpose: the flattened specimens are damaged precisely in
    their line endings and encodings, so any decoding would hide the damage.
    A directory hashes its files' relative paths and hashes in sorted order,
    bytecode caches included (a planted .pyc changes the hash). A symbolic
    link never hashes like the file it points at: it hashes as the text
    "symlink->target", so a specimen replaced by a link to identical content
    no longer matches. Missing paths give None.
    """
    target = Path(root) / rel
    if target.is_symlink():
        return _entry_hash("link", target)
    if target.is_file():
        return hashlib.sha256(target.read_bytes()).hexdigest()
    if target.is_dir():
        outer = hashlib.sha256()
        for sub, kind, path in sorted(_entries(target), key=lambda e: e[0]):
            outer.update(("/".join(sub) + "\0").encode("utf-8"))
            outer.update(_entry_hash(kind, path).encode("utf-8", "surrogateescape") + b"\n")
        return outer.hexdigest()
    return None


def corpus_files(root: Path) -> Dict[str, str]:
    """Hash of every entry under specimens/, registered or not.

    Bytecode caches, symbolic links and special files are listed too (a link
    as "symlink->target"), so each of them shows up as a change.
    """
    base = Path(root) / "specimens"
    out: Dict[str, str] = {}
    if base.is_symlink():
        out["specimens"] = _entry_hash("link", base)
    elif base.is_dir():
        for sub, kind, path in _entries(base):
            out[(Path("specimens") / Path(*sub)).as_posix()] = _entry_hash(kind, path)
    return dict(sorted(out.items()))


def corpus_layout_problems(root: Path, recorded: Optional[Dict[str, str]] = None) -> List[Tuple[str, str]]:
    """What must never be under specimens/, as (reason code, plain text).

    Symbolic links, special files and bytecode caches are always wrong. When
    the recorded list of files is given, any file that is not on it is wrong too.
    """
    base = Path(root) / "specimens"
    problems: List[Tuple[str, str]] = []
    if base.is_symlink():
        return [("symlink", "specimens/ is itself a symbolic link")]
    if not base.is_dir():
        return problems
    for sub, kind, path in _entries(base):
        name = (Path("specimens") / Path(*sub)).as_posix()
        if kind == "link":
            import os
            problems.append(("symlink", f"{name} is a symbolic link to {os.readlink(path)} (a specimen must be "
                                        "the file itself, even if the link points at identical content)"))
        elif kind == "special":
            problems.append(("unexpected_file", f"{name} is not a regular file"))
        elif is_bytecode(sub):
            problems.append(("bytecode", f"{name} is a compiled bytecode file; none belongs in the corpus and "
                                          "the verifier never imports one"))
        elif recorded is not None and name not in recorded:
            problems.append(("unexpected_file", f"{name} is not in the recorded list of specimen files"))
    return problems


def block_digest(block_text: str) -> str:
    """SHA-256 of the machine block's text, tolerant of Windows line endings."""
    return hashlib.sha256(block_text.replace("\r\n", "\n").encode("utf-8")).hexdigest()


# --- the machine block -----------------------------------------------------

def table_record(spec: dict) -> dict:
    """The part of a block record that comes from the table (no hashes)."""
    return {"id": spec["id"], "class": spec["cls"], "path": spec["path"],
            "companions": list(spec["companions"]), "verdict": spec["verdict"],
            "failure_mode": spec["failure_mode"], "section": spec["section"],
            "what": spec["what"], "prose": spec["prose"]}


def build_block(root: Path = ROOT) -> dict:
    """The machine block as it should read right now: table plus live file hashes."""
    check_table()
    records = []
    for spec in MANIFEST_SPECIMENS:
        rec = table_record(spec)
        rec["sha256"] = hash_path(root, spec["path"])
        rec["companion_sha256"] = {c: hash_path(root, c) for c in spec["companions"]}
        records.append(rec)
    return {"format": BLOCK_FORMAT, "records": records, "corpus_files": corpus_files(root)}


def block_to_text(block: dict) -> str:
    return json.dumps(block, indent=1, sort_keys=True, ensure_ascii=True)


def extract_block(manifest_text: str) -> Tuple[Optional[str], Optional[str]]:
    """(block json text, problem). Exactly one delimited block is allowed."""
    text = manifest_text.replace("\r\n", "\n")
    begins = _BLOCK_BEGIN_RE.findall(text)
    ends = text.count(BLOCK_END)
    if len(begins) != 1 or ends != 1:
        return None, (f"MANIFEST.md must contain exactly one machine block "
                      f"(found {len(begins)} begin marker(s) and {ends} end marker(s))")
    start = _BLOCK_BEGIN_RE.search(text).end()
    stop = text.index(BLOCK_END)
    if stop < start:
        return None, "MANIFEST.md machine block markers are in the wrong order"
    inner = text[start:stop]
    m = re.fullmatch(r"\s*```json\n(.*)\n```\s*", inner, re.S)
    if not m:
        return None, "the machine block in MANIFEST.md is not a single ```json fenced block"
    return m.group(1), None


def manifest_without_block(manifest_text: str) -> str:
    """The human prose only: everything outside the machine block."""
    text = manifest_text.replace("\r\n", "\n")
    m = _BLOCK_BEGIN_RE.search(text)
    if not m or BLOCK_END not in text:
        return text
    return text[:m.start()] + text[text.index(BLOCK_END) + len(BLOCK_END):]


BLOCK_SECTION_TITLE = "## Machine-readable answer key"
_BLOCK_INTRO = (
    "{title}\n\n"
    "The block below is the same answer key as the prose above, as data. It is generated by\n"
    "`python3 -m assay_production.manifest_registry --write` and checked by `verify_manifest.py`\n"
    "on every run. Do not edit it by hand: any difference from the table in\n"
    "`assay_production/manifest_registry.py`, from `assay_production/registry.json` or from the\n"
    "files on disk makes verification fail. It also records the SHA-256 of every file under\n"
    "`specimens/`, so a changed specimen is caught even if it still looks fine.\n\n"
)


def render_block_section(block_text: str) -> str:
    return (_BLOCK_INTRO.format(title=BLOCK_SECTION_TITLE) + BLOCK_BEGIN + "\n```json\n" + block_text +
            "\n```\n" + BLOCK_END + "\n")


def replace_block(manifest_text: str, block_text: str) -> str:
    """Swap the block's contents, or append the whole section if there is none yet."""
    text = manifest_text.replace("\r\n", "\n")
    if _BLOCK_BEGIN_RE.search(text) and BLOCK_END in text:
        start = _BLOCK_BEGIN_RE.search(text).start()
        stop = text.index(BLOCK_END) + len(BLOCK_END)
        return text[:start] + BLOCK_BEGIN + "\n```json\n" + block_text + "\n```\n" + BLOCK_END + text[stop:]
    return text.rstrip("\n") + "\n\n---\n\n" + render_block_section(block_text)


# --- the registry ----------------------------------------------------------

def build_manifest_registry(root: Path = ROOT, block: Optional[dict] = None,
                            statuses: Optional[Dict[str, dict]] = None) -> SpecimenRegistry:
    """Table plus hashes plus derived validation status, as a registry.

    Raises DuplicateSpecimenId rather than letting a later entry replace an
    earlier one.
    """
    check_table()
    block = block if block is not None else build_block(root)
    by_id = {r["id"]: r for r in block["records"]}
    digest = block_digest(block_to_text(block))
    registry = SpecimenRegistry(root)
    for spec in MANIFEST_SPECIMENS:
        rec = by_id[spec["id"]]
        status = (statuses or {}).get(spec["id"]) or {
            "manifest_status": "ANSWER_KEY_UNVALIDATED",
            "validation": {"level": "UNVALIDATED", "claims_asserted": [],
                           "reason": "no verification run has recorded a status for this entry"}}
        registry.register(SpecimenRecord(
            specimen_id=spec["id"], specimen_version="1.0.0",
            specimen_class=spec["cls"], source_revision="MANIFEST.md",
            path=spec["path"], expected_behavior=spec["what"],
            failure_mode=spec["failure_mode"], epistemic_status="RECORDED_IN_MANIFEST",
            provenance=f"ASSAY MANIFEST.md section {spec['section']}",
            intended_test=spec["cls"].lower(), expected_verdict=spec["verdict"],
            manifest_status=status["manifest_status"],
            tags=[spec["cls"].lower()],
            metadata={"manifest_section": spec["section"], "companions": list(spec["companions"])},
            sha256=rec["sha256"], companion_sha256=dict(rec["companion_sha256"]),
            manifest_block_sha256=digest, validation=status["validation"],
        ))
    return registry


def missing_paths(root: Path = ROOT) -> List[str]:
    """Every registered path, primary or companion, that does not exist."""
    out = []
    for spec in MANIFEST_SPECIMENS:
        for rel in [spec["path"], *spec["companions"]]:
            if not (Path(root) / rel).exists():
                out.append(f"{spec['id']}: {rel}")
    return out


def render(root: Path = ROOT, block: Optional[dict] = None, statuses: Optional[Dict[str, dict]] = None) -> str:
    reg = build_manifest_registry(root, block, statuses)
    data: Dict[str, dict] = {sid: rec.to_dict() for sid, rec in reg._records.items()}
    return json.dumps(data, indent=2, sort_keys=True) + "\n"


def registry_path(root: Path = ROOT) -> Path:
    return Path(root) / "assay_production" / "registry.json"


def load_registry_strict(path: Path) -> Tuple[Optional[dict], Optional[str]]:
    """Parse registry.json, refusing duplicate keys (JSON would silently keep the last)."""
    dupes: List[str] = []

    def pairs(items):
        seen: Dict[str, object] = {}
        for k, v in items:
            if k in seen:
                dupes.append(k)
            seen[k] = v
        return seen

    try:
        data = json.loads(Path(path).read_text(encoding="utf-8"), object_pairs_hook=pairs)
    except (OSError, ValueError) as exc:
        return None, f"registry.json cannot be read: {exc}"
    if dupes:
        return data, "registry.json repeats the id(s): " + ", ".join(sorted(set(dupes)))
    return data, None


def main(argv: List[str]) -> int:
    if "--write" in argv:
        from .verification import write_all
        return write_all(ROOT)
    problems = table_problems()
    if problems:
        print("refusing to print a registry from an unsound table:", file=sys.stderr)
        for p in problems:
            print("  " + p, file=sys.stderr)
        return 1
    missing = missing_paths()
    if missing:
        print("refusing to publish a registry that points at missing files:", file=sys.stderr)
        for m in missing:
            print("  " + m, file=sys.stderr)
        return 1
    # Printing shows the committed statuses, not freshly derived ones: deriving
    # them means running the specimens, and that only happens in --write.
    data, _ = load_registry_strict(registry_path())
    statuses = {sid: {"manifest_status": d.get("manifest_status", "ANSWER_KEY_UNVALIDATED"),
                      "validation": d.get("validation", {})} for sid, d in (data or {}).items()}
    sys.stdout.write(render(ROOT, statuses=statuses))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
