"""The checks behind `verify_manifest.py`, and the command that re-records the key.

Two jobs, one engine:

* `main()` (verify): run every claim, print PASS/FAIL lines, and exit non-zero
  on any failure, in plain words that say which verdict is now unprovable and
  what to do next.
* `write_all()` (--write): refuse to run unless the corpus still behaves as
  the claims say, then re-record the machine block in MANIFEST.md, every
  content hash, the validation status of every entry in registry.json, and
  the generated status block in README.md. Nothing else writes those.

What "validated" means here (and what it does not)
--------------------------------------------------
Each registry entry gets one of three levels, derived from what this run
really asserted, never typed by hand:

VERIFIED_BY_EXECUTION   the verifier ran the specimen (in the sandbox) and
                        asserted the behaviour its verdict names.
VERIFIED_BY_STATIC_CHECK the verdict is itself a property of the file text and
                        the verifier compared the text. Nothing was run.
UNVALIDATED             the verifier checked only that files exist, parse, are
                        still damaged as described, and are unchanged. The
                        verdict rests on a human judgement or an outside
                        measurement that this verifier does not repeat. The
                        entry says why.
"""
from __future__ import annotations

import ast
import hashlib
import json
import os
import re
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Dict, List, Optional, Sequence, Tuple

from . import manifest_registry as mr
from .manifest_status import ManifestVerifier
from . import sandbox as sandbox_module
from .sandbox import SandboxResult, describe_isolation, run_in_sandbox

EXECUTION = "VERIFIED_BY_EXECUTION"
STATIC = "VERIFIED_BY_STATIC_CHECK"
UNVALIDATED = "UNVALIDATED"

#: Similarity two files must share to count as "the same content" (3.3).
#: Measured on the real pair: 1.000, because the flattened copy is identical to
#: the canonical file once whitespace is removed. Measured between every other
#: pair of Python files in the corpus: the highest is 0.951 (a faithful
#: reconstruction beside its source), then 0.847 (two files of the same lineage),
#: and most pairs are far lower. 0.99 therefore accepts a real duplicate with
#: only trivial differences and rejects related-but-different files, which a
#: looser threshold would not. tests/test_verifier.py re-measures all of this.
SAME_CONTENT_THRESHOLD = 0.99
SHINGLE = 16

README_BEGIN = ("<!-- ASSAY-STATUS:BEGIN (generated by `python3 -m assay_production.manifest_registry "
                "--write` and checked by `verify_manifest.py`; do not edit by hand) -->")
README_END = "<!-- ASSAY-STATUS:END -->"
_README_BEGIN_RE = re.compile(r"<!-- ASSAY-STATUS:BEGIN[^>]*-->")

NEXT_DRIFT = ("If the change was an accident, put the file back (for example "
              "`git checkout -- <path>`). If it was deliberate, it is a change to the answer key: get it "
              "reviewed, re-measure the verdict, update MANIFEST.md and the table in "
              "assay_production/manifest_registry.py, then run "
              "`python3 -m assay_production.manifest_registry --write`.")
NEXT_REGEN = ("If you meant to change the answer key, run "
              "`python3 -m assay_production.manifest_registry --write` and commit the result for review. "
              "If you did not, undo the edit.")


# --------------------------------------------------------------------- model

@dataclass
class Claim:
    id: str
    label: str
    ok: bool
    kind: str = "static"            # "static", "execution" or "meta"
    entries: Tuple[str, ...] = ()    # registry entries this claim supports
    skipped: bool = False            # could not be asserted on this machine
    regen: bool = False              # --write is allowed to fix this one
    problem: str = ""
    next_step: str = ""
    unprovable: Tuple[str, ...] = ()  # entries named in the failure message (default: entries)
    consequence: str = ""             # replaces the "verdicts that can no longer be trusted" line
    reason: str = ""                  # short machine-readable cause: timeout, stray_write, hash_mismatch, ...


@dataclass
class Report:
    claims: List[Claim] = field(default_factory=list)
    notes: List[str] = field(default_factory=list)
    derived: Dict[str, dict] = field(default_factory=dict)
    skipped_entries: List[str] = field(default_factory=list)

    @property
    def by_id(self) -> Dict[str, Claim]:
        return {c.id: c for c in self.claims}

    @property
    def failures(self) -> List[Claim]:
        return [c for c in self.claims if not c.ok and not c.skipped]

    @property
    def skips(self) -> List[Claim]:
        return [c for c in self.claims if c.skipped]


@dataclass(frozen=True)
class Rule:
    level: str
    required: Tuple[str, ...] = ()
    gap: str = ""


_PAIR_GAP = ("The verdict rests on a class-name coverage measurement made on 2026-09-07 with an outside tool "
             "(blackhole_extrapolator), which this verifier does not repeat. It checks only that both files "
             "exist, the source is still one flattened line, and the reconstruction parses.")
_SUPERSEDED_GAP = ("The verdict is an editorial judgement (tried and replaced). There is no executable claim "
                   "to assert; the file is pinned only by its recorded hash.")
_RESKIN_GAP = ("The verifier checks only that both files still carry the shared 1e-4 and 1e-2 thresholds under "
               "different class names. It does not re-derive that the two energy formulas are the same "
               "(they are written over different sets of inputs).")

PAIR_SLUGS = {
    "governance_os_security": ("pair_governance_os_security", "pairs/governance_os_security_source.py",
                               "pairs/governance_os_security_adapter.py"),
    "quorum_state_governance": ("pair_quorum_state_governance", "pairs/quorum_state_governance_source.py",
                                "pairs/quorum_state_governance_adapter.py"),
    # Paired with _cleanup, not _adapter: the adapter is a lossier
    # consolidation of the same source and pairing against it recorded a false
    # "most divergent artifact in the corpus" verdict for a day.
    "solvar_stability_governance": ("pair_solvar_stability_governance",
                                    "pairs/solvar_stability_governance_source.py",
                                    "pairs/solvar_stability_governance_cleanup.py"),
    "sre_system_resilience": ("pair_sre_system_resilience", "pairs/sre-system-resilience-evaluator-flattened.py",
                              "pairs/sre_system_resilience_evaluator_adapter.py"),
    "vanguard_behavioral_simulation": ("pair_vanguard_behavioral_simulation",
                                       "pairs/vanguard-behavioral-simulation-flattened.py",
                                       "pairs/vanguard-behavioral-simulation.py"),
}

#: Reference implementations: slug -> (entry id, path under specimens/, marker the run must print or None)
REFERENCES = {
    "agent_factory": ("reference_agent_factory_tactical_agents", "reference/agent-factory-tactical-agents.py", None),
    "citadel": ("reference_citadel_v1_2", "reference/citadel_v1.2.py", None),
    "code_repo_governance": ("reference_code_repo_governance_and_gsa_core",
                             "reference/code-repo-governance-and-gsa-core.py", None),
    "resilience_kernel": ("reference_resilience_stability_kernel", "reference/resilience_stability_kernel.py",
                          "all property checks passed"),
    "solvar_cleanup": ("reference_solvar_stability_governance_cleanup",
                       "pairs/solvar_stability_governance_cleanup.py", None),
    "sandbox": ("reference_secure_artifact_2", "reference/secure/artifact_2.py", None),
}

RULES: Dict[str, Rule] = {
    "pair_solvar_stability_consolidation": Rule(UNVALIDATED, gap=_PAIR_GAP),
    "uztc_progression": Rule(EXECUTION, ("uztc.v10_not_parse", "uztc.v11_imports", "fm3_2.v12_raises")),
    "fm_3_1_silent_pass": Rule(EXECUTION, ("fm3_1.imports", "fm3_1.zero_names")),
    "fm_3_2_overclaim": Rule(EXECUTION, ("fm3_2.v12_raises",)),
    "fm_3_3_flattening_duplicate": Rule(STATIC, ("fm3_3.both_present", "fm3_3.secure_flattened",
                                                 "fm3_3.same_content")),
    "fm_3_4_unreachable_branch": Rule(EXECUTION, ("fm3_4.critical_unreachable",)),
    "fm_3_5_reskinned_duplicate": Rule(UNVALIDATED, gap=_RESKIN_GAP),
    "reference_sovereign_kernel": Rule(EXECUTION, ("ref.sovereign_kernel.runs_assembled",)),
    "reference_secure_artifact_2": Rule(EXECUTION, ("ref.sandbox.runs", "ref.sandbox.enforces")),
}
for _slug, (_eid, _p, _a) in PAIR_SLUGS.items():
    RULES[_eid] = Rule(UNVALIDATED, gap=_PAIR_GAP)
for _slug, (_eid, _p, _m) in REFERENCES.items():
    RULES.setdefault(_eid, Rule(EXECUTION, (f"ref.{_slug}.runs",)))
for _spec in mr.MANIFEST_SPECIMENS:
    if _spec["cls"] == "SUPERSEDED":
        RULES[_spec["id"]] = Rule(UNVALIDATED, gap=_SUPERSEDED_GAP)


# ------------------------------------------------------------------- helpers

def parses(path: Path) -> bool:
    try:
        ast.parse(path.read_text(errors="replace"))
        return True
    except SyntaxError:
        return False


def squash(text: str) -> str:
    """The text with every kind of whitespace removed: what flattening cannot change."""
    return re.sub(r"\s+", "", text)


def _shingles(text: str) -> set:
    s = squash(text)
    return {s[i:i + SHINGLE] for i in range(max(len(s) - SHINGLE + 1, 1))}


def content_similarity(a: str, b: str) -> float:
    """Share of 16-character runs (whitespace removed) the two texts have in common.

    1.0 means identical apart from whitespace; unrelated code scores close to
    0. This is the provenance test behind 'same content' (3.3): a file that is
    merely different and shorter no longer qualifies.
    """
    sa, sb = _shingles(a), _shingles(b)
    if not sa or not sb:
        return 0.0
    return len(sa & sb) / len(sa | sb)


def definition_coverage(canonical: str, other: str) -> float:
    """Share of the canonical file's top-level class/function names found in the other.

    The canonical file is parsed properly; the other may be flattened and not
    parse, so its text is searched with whitespace removed ('class' + name).
    """
    try:
        tree = ast.parse(canonical)
    except SyntaxError:
        return 0.0
    names = [n.name for n in tree.body if isinstance(n, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef))]
    if not names:
        return 0.0
    flat = squash(other)
    found = 0
    for n in names:
        kinds = ("class",) if n in {x.name for x in tree.body if isinstance(x, ast.ClassDef)} else ("def", "asyncdef")
        if any((k + n) in flat for k in kinds):
            found += 1
    return found / len(names)


def _verdicts() -> Dict[str, str]:
    return {s["id"]: s["verdict"] for s in mr.MANIFEST_SPECIMENS}


def entries_for_path(rel: str) -> List[str]:
    return [s["id"] for s in mr.MANIFEST_SPECIMENS if rel == s["path"] or rel in s["companions"]]


# ------------------------------------------------------------------ the run

_REASON_BY_PREFIX = (("hash.", "hash_mismatch"), ("specimens.layout", "unexpected_file"),
                     ("sandbox.guard", "stray_write"), ("sandbox.corpus_untouched", "stray_write"),
                     ("manifest.", "answer_key_drift"), ("registry.", "answer_key_drift"),
                     ("readme.", "answer_key_drift"), ("table.", "answer_key_drift"))


def default_reason(cid: str, kind: str) -> str:
    """A short cause for a failed claim that did not name its own (see Claim.reason)."""
    for prefix, reason in _REASON_BY_PREFIX:
        if cid.startswith(prefix):
            return reason
    if cid.startswith(("pair.", "uztc.", "fm3_", "fm_", "ref.")) and kind != "execution":
        return "specimen_changed"
    return "claim_failed"


class Verifier:
    def __init__(self, root: Path, *, strict: bool = False):
        self.root = Path(root)
        self.specimens = self.root / "specimens"
        self.strict = strict
        self.report = Report()
        self.sandbox_runs: List[Tuple[str, SandboxResult, Tuple[str, ...]]] = []
        self.deadline = time.monotonic() + sandbox_module.total_budget()

    # -- recording ----------------------------------------------------------
    def check(self, cid: str, label: str, ok: bool, *, kind: str = "static", entries: Sequence[str] = (),
              regen: bool = False, problem: str = "", next_step: str = "", unprovable: Sequence[str] = (),
              skipped: bool = False, consequence: str = "", reason: str = "") -> bool:
        self.report.claims.append(Claim(cid, label, bool(ok), kind, tuple(entries), skipped, regen, problem,
                                        next_step or NEXT_DRIFT, tuple(unprovable) or tuple(entries),
                                        consequence, "" if ok else (reason or default_reason(cid, kind))))
        return bool(ok)

    # -- sandbox ------------------------------------------------------------
    def run(self, name: str, mode: str, target: Path, entries: Sequence[str] = (), **kw) -> SandboxResult:
        res = run_in_sandbox(mode, target, deadline=self.deadline, **kw)
        self.sandbox_runs.append((name, res, tuple(entries)))
        return res

    def sandbox_problem(self, res: SandboxResult) -> str:
        return "; ".join(f"[{code}] {text}" for code, text in res.problems())

    def exec_claim(self, cid: str, label: str, entries: Sequence[str], res: SandboxResult,
                   condition: Callable[[SandboxResult], bool], *, expect_error: bool = False) -> bool:
        """Record a claim whose proof is a sandboxed run. A tripped guard always fails it."""
        if res.missing_dependency and not res.violations:
            self.check(cid, label + f" (not run: {res.missing_dependency} is not installed)", False,
                       kind="execution", entries=entries, skipped=True)
            self.report.skipped_entries.extend(e for e in entries if e not in self.report.skipped_entries)
            return False
        clean = res.clean and res.completed and not res.timed_out
        ok = clean and (expect_error or not res.error) and condition(res)
        problem = "" if ok else (self.sandbox_problem(res) or "the run did not show the behaviour the claim requires")
        reason = res.reason_code or "behaviour_changed"
        return self.check(cid, label, ok, kind="execution", entries=entries, problem=problem, reason=reason)

    # ---------------------------------------------------------------- phases
    def all(self) -> Report:
        before = mr.corpus_files(self.root)
        self.table_phase()
        self.layout_phase()
        self.pairs_phase()
        self.progression_phase()
        self.failure_modes_phase()
        self.references_phase()
        self.sandbox_phase(before)
        self.answer_key_phase()
        self.finish()
        return self.report

    # -- 0. table -----------------------------------------------------------
    def table_phase(self) -> None:
        problems = mr.table_problems()
        self.check("table.sound", "table: every specimen id is unique and every row is complete", not problems,
                   kind="meta", problem="; ".join(problems),
                   next_step="Fix assay_production/manifest_registry.py so every id appears once, then run "
                             "`python3 -m assay_production.manifest_registry --write`. Until then the registry "
                             "cannot be trusted: a repeated id silently replaces the earlier entry.",
                   unprovable=[p.split("'")[1] for p in problems if "duplicate" in p and "'" in p])

    # -- 0b. the folder itself -------------------------------------------------
    def layout_phase(self) -> None:
        problems = mr.corpus_layout_problems(self.root)
        codes = [c for c, _ in problems]
        self.check("specimens.layout",
                   "specimens/: only plain files (no symbolic links, special files or bytecode caches)",
                   not problems, kind="meta", problem="; ".join(t for _, t in problems[:10])
                   + (" ..." if len(problems) > 10 else ""),
                   reason=codes[0] if codes else "",
                   next_step="Delete the link, cache or special file, or restore the real specimen with git. "
                             "A link is refused even when it points at identical content: the verifier hashes "
                             "and runs files, and a link lets the content change without the hash noticing.",
                   unprovable=sorted({e for _, t in problems for e in entries_for_path(t.split(" ")[0])}))

    # -- 1. reconstruction pairs ---------------------------------------------
    def pairs_phase(self) -> None:
        for slug, (eid, source_rel, adapter_rel) in PAIR_SLUGS.items():
            source, adapter = self.specimens / source_rel, self.specimens / adapter_rel
            name = source.name
            self.check(f"pair.{slug}.intact", f"pair intact: {name} + {adapter.name}",
                       source.is_file() and adapter.is_file(), entries=[eid],
                       problem="one half of the pair is missing; a pair with a missing half is not a pair")
            if source.is_file():
                # Flattened: one enormous line. `wc -l` reports 0 because there
                # is no terminating newline on the single line.
                self.check(f"pair.{slug}.flattened", f"{name} still flattened (0 newline-terminated lines)",
                           source.read_bytes().count(b"\n") == 0, entries=[eid],
                           problem="the degraded source has line breaks again; it was reformatted or replaced")
            if adapter.is_file():
                self.check(f"pair.{slug}.parses", f"{adapter.name} still parses", parses(adapter), entries=[eid],
                           problem="the reconstruction no longer parses as Python")
        # The same source's second, lossier reconstruction.
        src = self.specimens / "pairs/solvar_stability_governance_source.py"
        alt = self.specimens / "pairs/solvar_stability_governance_adapter.py"
        eid = "pair_solvar_stability_consolidation"
        self.check("pair.solvar_consolidation.intact",
                   f"pair intact: {src.name} + {alt.name} (the lossier consolidation)",
                   src.is_file() and alt.is_file(), entries=[eid],
                   problem="one half of the consolidation pair is missing")
        if alt.is_file():
            self.check("pair.solvar_consolidation.parses", f"{alt.name} still parses", parses(alt), entries=[eid],
                       problem="the consolidated reconstruction no longer parses as Python")

    # -- 2. progression ------------------------------------------------------
    def progression_phase(self) -> None:
        uztc = self.specimens / "progressions/uztc"
        eid = "uztc_progression"
        self.check("uztc.v10_not_parse", "uztc v1.0 still does not parse",
                   not parses(uztc / "uztc-construct-v1.0-flattened.py"), entries=[eid],
                   problem="the flattened v1.0 now parses, so it is no longer the damaged original")
        self.check("uztc.v11_parses", "uztc v1.1 still parses", parses(uztc / "uztc-construct-v1.1-purged.py"),
                   entries=[eid], problem="v1.1 no longer parses")
        self.check("uztc.v12_parses", "uztc v1.2 still parses", parses(uztc / "uztc-construct-v1.2-validated.py"),
                   entries=[eid, "fm_3_2_overclaim"], problem="v1.2 no longer parses")
        res = self.run("uztc v1.1", "probe", uztc / "uztc-construct-v1.1-purged.py", [eid], probe="names")
        self.exec_claim("uztc.v11_imports", "uztc v1.1 imports without error", [eid], res, lambda r: True)

    # -- 3. failure modes ----------------------------------------------------
    def failure_modes_phase(self) -> None:
        uztc = self.specimens / "progressions/uztc"
        # 3.1 Silent pass: imports cleanly, defines nothing. The whole point is
        # that an importability check calls this healthy.
        silent = self.specimens / "pairs/governance_os_security_source.py"
        e31 = "fm_3_1_silent_pass"
        res = self.run("3.1 silent pass", "probe", silent, [e31], probe="names")
        self.exec_claim("fm3_1.imports", "3.1 silent pass: imports without error", [e31], res, lambda r: True)
        self.exec_claim("fm3_1.zero_names", "3.1 silent pass: defines zero names", [e31], res,
                        lambda r: r.probe.get("names") == [])

        # 3.2 Overclaim: v1.2 presents as the refined endpoint and cannot run.
        res = self.run("3.2 overclaim", "probe", uztc / "uztc-construct-v1.2-validated.py",
                       ["fm_3_2_overclaim", "uztc_progression"], probe="uztc_validate")
        self.exec_claim("fm3_2.v12_raises", "3.2 overclaim: v1.2 still raises AttributeError",
                        ["fm_3_2_overclaim", "uztc_progression"], res,
                        lambda r: r.probe.get("raised") == "AttributeError")

        # 3.3 Flattening duplicate: same content, one flattened, one not.
        e33 = "fm_3_3_flattening_duplicate"
        canonical = self.specimens / "reference/wrapper/artifact_3.py"
        flattened = self.specimens / "reference/secure/artifact_1.py"
        both = canonical.is_file() and flattened.is_file()
        self.check("fm3_3.both_present", "3.3 flattening duplicate: both halves present", both, entries=[e33],
                   problem="one of the two duplicate files is missing")
        if both:
            cb, fb = canonical.read_bytes(), flattened.read_bytes()
            self.check("fm3_3.differ", "3.3 flattening duplicate: copies still differ textually", cb != fb,
                       entries=[e33], problem="the two files are now byte-identical, so nothing is flattened")
            self.check("fm3_3.secure_flattened", "3.3 flattening duplicate: secure/ copy still the flattened one",
                       fb.count(b"\n") < cb.count(b"\n"), entries=[e33],
                       problem="the secure/ copy no longer has fewer line breaks than the canonical file")
            # Provenance: 'real duplicate' means the same code, not two merely
            # different files. Compare with whitespace removed, so flattening
            # cannot hide a match and unrelated files cannot fake one.
            ct, ft = cb.decode("utf-8", "replace"), fb.decode("utf-8", "replace")
            sim, cover = content_similarity(ct, ft), definition_coverage(ct, ft)
            ok = sim >= SAME_CONTENT_THRESHOLD and cover >= SAME_CONTENT_THRESHOLD
            self.check("fm3_3.same_content",
                       f"3.3 flattening duplicate: same content once whitespace is ignored "
                       f"(text similarity {sim:.3f}, definition names shared {cover:.3f}, "
                       f"both must be at least {SAME_CONTENT_THRESHOLD})", ok, entries=[e33],
                       problem=(f"the two files share only {sim:.0%} of their text and {cover:.0%} of the "
                                f"canonical file's class and function names. They are no longer the same code "
                                f"in two layouts, so 'same content' cannot be proven."))

        # 3.4 Unreachable branch: the adapter's own self-test searches 100,000
        # inputs for a CRITICAL verdict and asserts there is none. Its kernel
        # must sit beside it, as the adapter's header says.
        adapter = self.specimens / "pairs/sre_system_resilience_evaluator_adapter.py"
        kernel = self.specimens / "reference/resilience_stability_kernel.py"
        if adapter.is_file() and kernel.is_file():
            res = self.run("3.4 unreachable", "script", adapter, ["fm_3_4_unreachable_branch"],
                           stage=[(kernel, "resilience_stability_kernel.py")])
            self.exec_claim(
                "fm3_4.critical_unreachable",
                "3.4 unreachable branch: the adapter's 100,000-sample search still finds no CRITICAL verdict",
                ["fm_3_4_unreachable_branch"], res,
                lambda r: r.exit_code == 0 and "found_critical=False" in r.stdout
                and "ALL SRE RECONSTRUCTION CHECKS PASSED" in r.stdout)
        else:
            self.check("fm3_4.critical_unreachable", "3.4 unreachable branch: adapter and kernel present", False,
                       kind="execution", entries=["fm_3_4_unreachable_branch"],
                       problem="the SRE adapter or the shared kernel file is missing")

        # 3.5 Reskinned duplicate (static only; see _RESKIN_GAP).
        solvar = self.specimens / "pairs/solvar_stability_governance_adapter.py"
        if solvar.is_file() and adapter.is_file():
            st, at = solvar.read_text(errors="replace"), adapter.read_text(errors="replace")
            ok = ("1e-4" in st and "1e-2" in st and "1e-4" in at and "1e-2" in at
                  and "class LyapunovStabilityModule" in st and "class SystemStabilityValidator" in at
                  and "class LyapunovStabilityModule" not in at and "class SystemStabilityValidator" not in st)
            self.check("fm3_5.shared_thresholds",
                       "3.5 reskinned duplicate: both files still carry the 1e-4 / 1e-2 thresholds "
                       "under different class names", ok, entries=["fm_3_5_reskinned_duplicate"],
                       problem="the shared thresholds or the two different class names are no longer there")

    # -- 4. references -------------------------------------------------------
    def references_phase(self) -> None:
        # These must remain runnable. A corpus of only broken material cannot
        # test whether a verifier ever correctly says yes.
        sandbox = self.specimens / "reference/secure/artifact_2.py"
        self.check("ref.sandbox_present", "reference sandbox present", sandbox.is_file(),
                   entries=["reference_secure_artifact_2"], problem="the reference sandbox file is missing")
        if sandbox.is_file():
            res = self.run("reference sandbox", "probe", sandbox, ["reference_secure_artifact_2"],
                           probe="capability_denied")
            self.exec_claim("ref.sandbox.enforces", "reference sandbox still enforces capabilities",
                            ["reference_secure_artifact_2"], res,
                            lambda r: r.probe.get("raised") == "CapabilityError")
        # Each reference runs as a script, in the sandbox, and must exit 0.
        for slug, (eid, rel, marker) in REFERENCES.items():
            path = self.specimens / rel
            claim = "ref.sandbox.runs" if slug == "sandbox" else f"ref.{slug}.runs"
            if not path.is_file():
                self.check(claim, f"reference {Path(rel).name} runs", False, kind="execution", entries=[eid],
                           problem="the reference file is missing")
                continue
            res = self.run(f"reference {Path(rel).name}", "script", path, [eid])
            self.exec_claim(claim, f"reference {Path(rel).name} runs as a script and exits 0"
                            + (f" and prints '{marker}'" if marker else ""), [eid], res,
                            lambda r, m=marker: r.exit_code == 0 and (m is None or m in r.stdout))
        # sovereign_kernel.py loads five sibling files from its own folder. The
        # corpus keeps three of them in pairs/ (a layout fact the manifest does
        # not mention), so it cannot run in place; it runs once they are placed
        # beside it, which is what this claim says.
        ref = self.specimens / "reference"
        pairs = self.specimens / "pairs"
        kernel = ref / "sovereign_kernel.py"
        siblings = [(ref / "citadel_v1.2.py", "citadel_v1.2.py"),
                    (ref / "code-repo-governance-and-gsa-core.py", "code-repo-governance-and-gsa-core.py"),
                    (pairs / "sre_system_resilience_evaluator_adapter.py", "sre_system_resilience_evaluator_adapter.py"),
                    (pairs / "vanguard-behavioral-simulation.py", "vanguard-behavioral-simulation.py"),
                    (pairs / "quorum_state_governance_adapter.py", "quorum_state_governance_adapter.py"),
                    (ref / "resilience_stability_kernel.py", "resilience_stability_kernel.py")]
        if kernel.is_file() and all(s.is_file() for s, _ in siblings):
            res = self.run("reference sovereign_kernel", "script", kernel, ["reference_sovereign_kernel"],
                           stage=siblings)
            self.exec_claim("ref.sovereign_kernel.runs_assembled",
                            "reference sovereign_kernel.py runs and passes its own checks once the siblings it "
                            "loads are placed beside it",
                            ["reference_sovereign_kernel"], res,
                            lambda r: r.exit_code == 0 and "ALL SOVEREIGN_KERNEL DEMO CHECKS PASSED" in r.stdout)
        else:
            self.check("ref.sovereign_kernel.runs_assembled", "reference sovereign_kernel.py and its siblings present",
                       False, kind="execution", entries=["reference_sovereign_kernel"],
                       problem="sovereign_kernel.py or one of the files it loads is missing")

    # -- sandbox bookkeeping --------------------------------------------------
    def sandbox_phase(self, corpus_before: Dict[str, str]) -> None:
        violations = [f"{n}: {v}" for n, r, _ in self.sandbox_runs for v in r.violations]
        stray = [f"{n}: {s}" for n, r, _ in self.sandbox_runs for s in r.stray_files]
        flagged = sorted({e for _, r, es in self.sandbox_runs if r.violations or r.stray_files for e in es})
        self.check("sandbox.guard",
                   "sandbox: no specimen tried to write outside its scratch directory, start a program or use the network",
                   not violations and not stray, kind="meta",
                   problem="; ".join(violations + stray),
                   reason="violation" if violations else "stray_write",
                   next_step="Read the specimen named above before running it again anywhere that matters. "
                             "A specimen that reaches outside its scratch folder cannot be verified safely, "
                             "so the verdicts that depend on it are unprovable until it is removed or fixed. "
                             "Only the specimen's own source folder and the sandbox's control directory are "
                             "compared, never the shared /tmp, so other programs' temp files are not the cause.",
                   unprovable=flagged)
        after = mr.corpus_files(self.root)
        changed = sorted(set(corpus_before) ^ set(after)
                         | {k for k in corpus_before if k in after and corpus_before[k] != after[k]})
        self.check("sandbox.corpus_untouched", "sandbox: running the specimens changed no file under specimens/",
                   before_after_equal(corpus_before, after), kind="meta",
                   problem="files under specimens/ differ before and after the run: " + ", ".join(changed),
                   reason="stray_write",
                   next_step="Restore the files with git and find out which specimen wrote to the corpus.")

    # -- 6. the answer key itself ---------------------------------------------
    def answer_key_phase(self) -> None:
        root = self.root
        verdicts = _verdicts()
        # (a) registered files exist
        try:
            missing = mr.missing_paths(root)
        except Exception as exc:  # noqa: BLE001
            missing = [f"cannot check ({type(exc).__name__}: {exc})"]
        self.check("registry.files_exist", "registry: every registered specimen file exists", not missing,
                   kind="meta", problem="missing: " + "; ".join(missing),
                   unprovable=[m.split(":")[0] for m in missing])

        # (b) the machine block in MANIFEST.md
        manifest_path = root / "MANIFEST.md"
        manifest_text = manifest_path.read_text(encoding="utf-8", errors="replace") if manifest_path.is_file() else ""
        block_text, block_problem = mr.extract_block(manifest_text) if manifest_text else (None, "MANIFEST.md is missing")
        block: Optional[dict] = None
        if block_text is not None:
            try:
                block = json.loads(block_text, object_pairs_hook=_no_duplicate_keys)
            except ValueError as exc:
                block_problem = f"the machine block in MANIFEST.md is not valid JSON ({exc})"
        self.check("manifest.block_present", "manifest: MANIFEST.md carries one readable machine block",
                   block is not None, kind="meta", regen=True,
                   problem=block_problem or "", next_step=NEXT_REGEN, unprovable=list(verdicts))
        table_ok = not mr.table_problems()
        if block is not None and table_ok:
            self.compare_block_to_table(block, verdicts)
            self.compare_hashes(block, verdicts)
        elif block is not None:
            self.check("manifest.block_matches_table", "manifest: machine block agrees with the table", False,
                       kind="meta", problem="the table is unsound (see the first failure), so it cannot be compared",
                       unprovable=list(verdicts))
        self.prose_checks(manifest_text)

        # (c) registry.json
        self.registry_checks(block, block_text, table_ok)
        # (d) README
        self.readme_check()

    def compare_block_to_table(self, block: dict, verdicts: Dict[str, str]) -> None:
        lines: List[str] = []
        affected: List[str] = []
        recs = block.get("records") if isinstance(block, dict) else None
        if not isinstance(recs, list):
            self.check("manifest.block_matches_table", "manifest: machine block agrees with the table", False,
                       kind="meta", regen=True, problem="the machine block has no list of records",
                       next_step=NEXT_REGEN, unprovable=list(verdicts))
            return
        seen: Dict[str, dict] = {}
        for rec in recs:
            rid = rec.get("id") if isinstance(rec, dict) else None
            if rid in seen:
                lines.append(f"MANIFEST.md block repeats the id {rid!r}")
                affected.append(rid)
            seen[rid] = rec if isinstance(rec, dict) else {}
        table = {s["id"]: mr.table_record(s) for s in mr.MANIFEST_SPECIMENS}
        for sid in table:
            if sid not in seen:
                lines.append(f"{sid} is in the table but not in the MANIFEST.md block")
                affected.append(sid)
        for sid in seen:
            if sid not in table:
                lines.append(f"{sid} is in the MANIFEST.md block but not in the table")
                affected.append(sid)
        for sid, expect in table.items():
            got = seen.get(sid)
            if got is None:
                continue
            for key, want in expect.items():
                if got.get(key) != want:
                    lines.append(f"{sid}: {key} is {_short(want)} in the table but {_short(got.get(key))} "
                                 f"in the MANIFEST.md block")
                    affected.append(sid)
        self.check("manifest.block_matches_table",
                   "manifest: machine block agrees with the table (id, class, path, companions, verdict) in both directions",
                   not lines, kind="meta", regen=True, problem="; ".join(lines[:12]) + (" ..." if len(lines) > 12 else ""),
                   next_step=("The table in assay_production/manifest_registry.py and the machine block in "
                              "MANIFEST.md must say the same thing. If you meant to change an answer, change the "
                              "prose in MANIFEST.md as well, then run "
                              "`python3 -m assay_production.manifest_registry --write` and have the change "
                              "reviewed. If you did not, undo the edit."),
                   unprovable=sorted(set(affected)))

    def compare_hashes(self, block: dict, verdicts: Dict[str, str]) -> None:
        recorded = {r.get("id"): r for r in block.get("records", []) if isinstance(r, dict)}
        bad: List[str] = []
        who: List[str] = []
        for spec in mr.MANIFEST_SPECIMENS:
            rec = recorded.get(spec["id"])
            if rec is None:
                continue
            live = mr.hash_path(self.root, spec["path"])
            if live != rec.get("sha256"):
                bad.append(f"{spec['path']} no longer matches its recorded SHA-256 (used by {spec['id']}, "
                           f"verdict {spec['verdict']})")
                who.append(spec["id"])
            for comp in spec["companions"]:
                live = mr.hash_path(self.root, comp)
                if live != (rec.get("companion_sha256") or {}).get(comp):
                    bad.append(f"{comp} no longer matches its recorded SHA-256 (companion of {spec['id']}, "
                               f"verdict {spec['verdict']})")
                    who.append(spec["id"])
        self.check("hash.registered",
                   "specimen content: every registered specimen file still matches its recorded SHA-256",
                   not bad, kind="meta", regen=True, problem="; ".join(bad[:10]) + (" ..." if len(bad) > 10 else ""),
                   next_step=NEXT_DRIFT, unprovable=sorted(set(who)))
        files = block.get("corpus_files") if isinstance(block.get("corpus_files"), dict) else {}
        live_files = mr.corpus_files(self.root)
        changed = sorted(p for p in files if p in live_files and files[p] != live_files[p])
        gone = sorted(p for p in files if p not in live_files)
        new = sorted(p for p in live_files if p not in files)
        msgs = []
        who2: List[str] = []
        for p in changed:
            hit = entries_for_path(p)
            msgs.append(f"{p} changed" + (f" (used by {', '.join(f'{e} [{verdicts[e]}]' for e in hit)})" if hit else
                                           " (not a registered specimen, but SWIZZLE still scans it)"))
            who2 += hit
        for p in gone:
            hit = entries_for_path(p)
            msgs.append(f"{p} was removed" + (f" (used by {', '.join(hit)})" if hit else ""))
            who2 += hit
        for p in new:
            msgs.append(f"{p} was added and is not in the recorded list")
        self.check("hash.corpus",
                   "specimen content: no file under specimens/ was added, removed or changed since it was recorded",
                   not msgs, kind="meta", regen=True, problem="; ".join(msgs[:10]) + (" ..." if len(msgs) > 10 else ""),
                   next_step=NEXT_DRIFT, unprovable=sorted(set(who2)))

    def prose_checks(self, manifest_text: str) -> None:
        prose = mr.manifest_without_block(manifest_text) if manifest_text else ""
        lines = prose.split("\n")
        problems: List[str] = []
        affected: List[str] = []
        sections: Dict[str, str] = {}

        def section_text(find: str) -> Optional[str]:
            hits = [i for i, ln in enumerate(lines) if ln.startswith(find)]
            if len(hits) != 1:
                return None
            start = hits[0]
            level = len(lines[start]) - len(lines[start].lstrip("#"))
            end = len(lines)
            for j in range(start + 1, len(lines)):
                ln = lines[j]
                if ln.startswith("#") and (len(ln) - len(ln.lstrip("#"))) <= level:
                    end = j
                    break
            return " ".join(" ".join(lines[start:end]).split())

        for spec in mr.MANIFEST_SPECIMENS:
            marker = spec["prose"]
            if marker["unit"] == "row":
                rows = [ln for ln in lines if ln.startswith(marker["find"])]
                hay = [" ".join(r.split()) for r in rows]
                if not rows:
                    problems.append(f"{spec['id']}: MANIFEST.md has no table row starting {marker['find']!r}")
                    affected.append(spec["id"])
                    continue
                text = " ".join(hay)
            else:
                if marker["find"] not in sections:
                    sections[marker["find"]] = section_text(marker["find"]) or ""
                text = sections[marker["find"]]
                if not text:
                    problems.append(f"{spec['id']}: MANIFEST.md has no single heading starting {marker['find']!r}")
                    affected.append(spec["id"])
                    continue
            for phrase in marker["says"]:
                if " ".join(phrase.split()) not in text:
                    problems.append(f"{spec['id']}: the MANIFEST.md prose no longer says {phrase!r}, so the "
                                    f"recorded verdict {spec['verdict']} is not what the manifest states")
                    affected.append(spec["id"])
        # Both directions for the lists humans maintain: pair rows, reference rows, failure-mode headings.
        prose_sources = {m.group(1) for ln in lines for m in [re.match(r"\| `([^`]+)` \|", ln)] if m
                         and ln.count("|") >= 6 and re.search(r"flattened|source", m.group(1))}
        table_sources = {Path(s["path"]).name for s in mr.MANIFEST_SPECIMENS if s["cls"] == "RECONSTRUCTION_PAIR"}
        for extra in sorted(prose_sources - table_sources):
            problems.append(f"MANIFEST.md lists a reconstruction pair for {extra} that the table does not have")
        sec5 = section_text("## 5.") or ""
        row_names = set()
        for ln in lines:
            if re.match(r"\| `", ln) and "`" in ln:
                first_cell = ln.split("|")[1]
                if "## 5." and any(ln.startswith(p) for p in ("| `sovereign_kernel", "| `secure/", "| `code-repo", "| `resilience_", "| `citadel_")):
                    row_names |= set(re.findall(r"`([^`]+\.py)`", first_cell))
        table_refs = {s["path"].split("/", 2)[2] if s["path"].startswith("specimens/reference/") else Path(s["path"]).name
                      for s in mr.MANIFEST_SPECIMENS if s["cls"] == "REFERENCE"}
        for extra in sorted(row_names - table_refs):
            problems.append(f"MANIFEST.md section 5 lists the reference {extra} that the table does not have")
        for gone in sorted(table_refs - row_names):
            problems.append(f"the table has the reference {gone} but MANIFEST.md section 5 does not list it")
            affected += [s["id"] for s in mr.MANIFEST_SPECIMENS if s["path"].endswith(gone)]
        headings = {m.group(1) for ln in lines for m in [re.match(r"### (3\.\d)\b", ln)] if m}
        table_sections = {s["section"] for s in mr.MANIFEST_SPECIMENS if s["cls"] == "FAILURE_MODE"}
        for extra in sorted(headings - table_sections):
            problems.append(f"MANIFEST.md has a failure mode section {extra} that the table does not have")
        for gone in sorted(table_sections - headings):
            problems.append(f"the table has failure mode {gone} but MANIFEST.md has no such section")
            affected += [s["id"] for s in mr.MANIFEST_SPECIMENS if s["section"] == gone]
        self.check("manifest.prose_matches",
                   "manifest: the human-readable MANIFEST.md prose still states every recorded verdict",
                   not problems, kind="meta", problem="; ".join(problems[:10]) + (" ..." if len(problems) > 10 else ""),
                   next_step=("MANIFEST.md prose, the table and the machine block must agree. If the prose "
                              "was edited by mistake, undo it. If the answer really changed, update the table "
                              "(and its prose marker) in assay_production/manifest_registry.py as well, run "
                              "`python3 -m assay_production.manifest_registry --write`, and have the change reviewed."),
                   unprovable=sorted(set(affected)))

    def registry_checks(self, block: Optional[dict], block_text: Optional[str], table_ok: bool) -> None:
        path = mr.registry_path(self.root)
        data0, _ = mr.load_registry_strict(path) if path.is_file() else (None, None)
        self.report.derived = self.derive_statuses(data0 if isinstance(data0, dict) else {})
        self.check("registry.published", "registry: registry.json is published", path.is_file(), kind="meta",
                   regen=True, problem="assay_production/registry.json does not exist", next_step=NEXT_REGEN,
                   unprovable=list(_verdicts()))
        if not path.is_file():
            return
        data, dup_problem = mr.load_registry_strict(path)
        table_ids = [s["id"] for s in mr.MANIFEST_SPECIMENS]
        count_msgs = []
        if data is None:
            count_msgs.append(dup_problem or "registry.json cannot be read")
        else:
            if dup_problem:
                count_msgs.append(dup_problem)
            if len(data) != len(set(table_ids)):
                count_msgs.append(f"registry.json holds {len(data)} entries but the table has "
                                  f"{len(set(table_ids))} distinct ids")
            for sid in sorted(set(table_ids) - set(data)):
                count_msgs.append(f"{sid} is in the table but not in registry.json")
            for sid in sorted(set(data) - set(table_ids)):
                count_msgs.append(f"{sid} is in registry.json but not in the table")
            if block is not None:
                nrec = len(block.get("records", []))
                if nrec != len(data):
                    count_msgs.append(f"the MANIFEST.md block has {nrec} records but registry.json has {len(data)}")
        self.check("registry.counts", "registry: ids are unique and the counts agree (table, MANIFEST.md block, registry.json)",
                   not count_msgs, kind="meta", regen=True, problem="; ".join(count_msgs[:10]), next_step=NEXT_REGEN,
                   unprovable=list(_verdicts()) if count_msgs else ())
        if not table_ok:
            self.check("registry.matches_table",
                       "registry: registry.json matches manifest_registry.py (regenerate with: "
                       "python3 -m assay_production.manifest_registry --write)", False, kind="meta",
                       problem="the table is unsound, so no expected registry can be built", unprovable=list(_verdicts()))
            return

        derived = self.report.derived
        # What registry.json should say: table + the hashes recorded in the block + derived statuses.
        recorded_block = _block_with_recorded_hashes(self.root, block)
        try:
            expected_text = mr.render(self.root, recorded_block, derived)
            expected_data = json.loads(expected_text)
        except Exception as exc:  # noqa: BLE001
            self.check("registry.matches_table", "registry: registry.json matches manifest_registry.py",
                       False, kind="meta", problem=f"the expected registry could not be built ({type(exc).__name__}: {exc})")
            return
        actual_text = path.read_text(encoding="utf-8")
        diffs = _registry_diffs(data or {}, expected_data)
        digest_ok = True
        if block_text is not None and data:
            digest = mr.block_digest(block_text)
            digest_ok = all(d.get("manifest_block_sha256") == digest for d in data.values())
            if not digest_ok:
                diffs.append("manifest_block_sha256 in registry.json is not the SHA-256 of the machine block now in MANIFEST.md")
        # Statuses get their own claim so the message can say what was (not) asserted.
        status_diffs = [d for d in diffs if "validation" in d or "manifest_status" in d]
        other_diffs = [d for d in diffs if d not in status_diffs]
        self.check("registry.statuses", "registry: each entry's validation status is what this run really asserted",
                   not status_diffs, kind="meta", regen=True,
                   problem="; ".join(status_diffs[:8]) + (" ..." if len(status_diffs) > 8 else ""),
                   next_step="Statuses are derived from what the verifier actually asserted, never typed. "
                             "If a specimen stopped passing a claim, fix that first. Otherwise run "
                             "`python3 -m assay_production.manifest_registry --write` to re-record them.",
                   consequence="The validation level recorded for these entries is wrong. The specimens and their "
                               "verdicts may be fine, but the registry would tell SWIZZLE and Warden the "
                               "wrong thing about how much of the key was proven.")
        self.check("registry.matches_table",
                   "registry: registry.json matches manifest_registry.py (regenerate with: "
                   "python3 -m assay_production.manifest_registry --write)",
                   actual_text == expected_text, kind="meta", regen=True,
                   problem=("; ".join(other_diffs[:10]) if other_diffs else
                            "registry.json differs from the registry generated from the table, the MANIFEST.md "
                            "block and this run (formatting, field order or an extra field)"),
                   next_step=("registry.json is generated, never hand-edited. If you changed an answer on purpose, "
                              "run `python3 -m assay_production.manifest_registry --write` and have the result "
                              "reviewed. If you did not, restore the file with git."),
                   consequence="SWIZZLE and Warden read registry.json. If it is not the key MANIFEST.md states, "
                               "every score computed from it is a score against a different answer key: the "
                               "verdicts of the entries named above cannot be trusted until it is regenerated.")

    def derive_statuses(self, previous: dict) -> Dict[str, dict]:
        claims = self.report.by_id
        out: Dict[str, dict] = {}
        for spec in mr.MANIFEST_SPECIMENS:
            sid = spec["id"]
            rule = RULES.get(sid)
            if rule is None:
                rule = Rule(UNVALIDATED, gap="no executable claim is defined for this entry")
            related_ok = sorted(c.id for c in self.report.claims if sid in c.entries and c.ok and not c.skipped)
            if rule.level == UNVALIDATED:
                out[sid] = _status(UNVALIDATED, [], [], related_ok, rule.gap)
                continue
            req = [claims.get(cid) for cid in rule.required]
            if any(c is None for c in req):
                out[sid] = _status(UNVALIDATED, [], [], related_ok, "a claim this status depends on is not defined")
            elif any(c.skipped for c in req if c):
                old = previous.get(sid) if isinstance(previous, dict) else None
                if old and old.get("validation"):
                    out[sid] = {"manifest_status": old.get("manifest_status", "ANSWER_KEY_UNVALIDATED"),
                                "validation": old["validation"]}
                    if sid not in self.report.skipped_entries:
                        self.report.skipped_entries.append(sid)
                else:
                    out[sid] = _status(UNVALIDATED, [], [], related_ok,
                                       "its claims could not be run on this machine (a required library is missing)")
            elif all(c.ok for c in req if c):
                out[sid] = _status(rule.level, list(rule.required), [c.label for c in req if c],
                                   [i for i in related_ok if i not in rule.required], "")
            else:
                failed = [c.id for c in req if c and not c.ok]
                out[sid] = _status(UNVALIDATED, [], [], related_ok, "claim(s) failing: " + ", ".join(failed))
        return out

    def readme_check(self) -> None:
        readme = self.root / "README.md"
        text = readme.read_text(encoding="utf-8") if readme.is_file() else ""
        m = _README_BEGIN_RE.search(text)
        statuses = self.report.derived
        if not statuses:
            self.check("readme.status_block", "readme: the generated status block matches the answer key", False,
                       kind="meta", regen=True, problem="statuses could not be derived (see earlier failures)",
                       next_step=NEXT_REGEN)
            return
        expected = readme_block(self.root, statuses)
        if not m or README_END not in text:
            self.check("readme.status_block", "readme: the generated status block matches the answer key", False,
                       kind="meta", regen=True,
                       problem="README.md has no status block between its ASSAY-STATUS markers",
                       next_step=NEXT_REGEN)
            return
        current = text[m.start(): text.index(README_END) + len(README_END)]
        self.check("readme.status_block", "readme: the generated status block matches the answer key",
                   current == expected, kind="meta", regen=True,
                   consequence="The README tells readers how much of the key is proven. Those numbers no longer "
                                "match what the verifier found, so the README would overclaim or underclaim.",
                   problem="the counts printed in README.md are not the counts this run derived",
                   next_step="README.md's status block is generated so its numbers cannot drift. Run "
                             "`python3 -m assay_production.manifest_registry --write`.")

    def finish(self) -> None:
        pass


# -------------------------------------------------------------- small helpers

def before_after_equal(a: Dict[str, str], b: Dict[str, str]) -> bool:
    return a == b


def _no_duplicate_keys(items):
    seen = {}
    for k, v in items:
        if k in seen:
            raise ValueError(f"repeated key {k!r}")
        seen[k] = v
    return seen


def _short(value) -> str:
    text = json.dumps(value, sort_keys=True)
    return text if len(text) <= 60 else text[:57] + "..."


def _status(level: str, asserted: List[str], what: List[str], other: List[str], reason: str) -> dict:
    return {"manifest_status": "ANSWER_KEY_" + level,
            "validation": {"level": level, "claims_asserted": asserted, "what_was_asserted": what,
                           "other_claims_checked": other, "reason": reason}}


def _block_with_recorded_hashes(root: Path, block: Optional[dict]) -> dict:
    """Table records carrying the hashes the MANIFEST.md block recorded (live hashes if there is none)."""
    live = mr.build_block(root)
    if not isinstance(block, dict):
        return live
    recorded = {r.get("id"): r for r in block.get("records", []) if isinstance(r, dict)}
    for rec in live["records"]:
        old = recorded.get(rec["id"])
        if old:
            rec["sha256"] = old.get("sha256")
            rec["companion_sha256"] = old.get("companion_sha256", {})
    if isinstance(block.get("corpus_files"), dict):
        live["corpus_files"] = block["corpus_files"]
    return live


def _registry_diffs(actual: dict, expected: dict) -> List[str]:
    out: List[str] = []
    for sid in sorted(set(actual) | set(expected)):
        a, e = actual.get(sid), expected.get(sid)
        if a is None:
            out.append(f"{sid}: expected in registry.json but missing")
            continue
        if e is None:
            out.append(f"{sid}: in registry.json but not in the answer key")
            continue
        for key in sorted(set(a) | set(e)):
            if a.get(key) != e.get(key):
                if key in ("manifest_block_sha256",):
                    continue
                out.append(f"{sid}: {key} is {_short(a.get(key))} in registry.json but should be {_short(e.get(key))}")
    return out


# -------------------------------------------------------------------- README

_IMPORT_RE = {"numpy": re.compile(r"^\s*(?:import|from)\s+numpy\b", re.M),
              "matplotlib": re.compile(r"^\s*(?:import|from)\s+matplotlib\b", re.M)}
_TODO_RE = re.compile(r"\b" + "TO" + "DO" + r"\b")


def count_todo_markers(root: Path) -> int:
    """Unfinished-work markers in the specimens, the manifest and the code (README and tests excluded)."""
    paths = [p for p in (Path(root) / "specimens").rglob("*") if p.is_file() and "__pycache__" not in p.parts]
    paths += [Path(root) / "MANIFEST.md", Path(root) / "verify_manifest.py"]
    paths += sorted((Path(root) / "assay_production").glob("*.py"))
    return sum(len(_TODO_RE.findall(p.read_text(encoding="utf-8", errors="replace")))
               for p in paths if p.is_file() and p.suffix in (".py", ".md", ".txt", ""))


def import_counts(root: Path) -> Dict[str, int]:
    files = [p for p in (Path(root) / "specimens").rglob("*.py") if "__pycache__" not in p.parts]
    texts = [p.read_text(encoding="utf-8", errors="replace") for p in files]
    return {name: sum(1 for t in texts if rx.search(t)) for name, rx in _IMPORT_RE.items()}


def readme_block(root: Path, statuses: Dict[str, dict]) -> str:
    levels = {EXECUTION: 0, STATIC: 0, UNVALIDATED: 0}
    for st in statuses.values():
        levels[st["validation"]["level"]] += 1
    by_class: Dict[str, int] = {}
    for s in mr.MANIFEST_SPECIMENS:
        by_class[s["cls"]] = by_class.get(s["cls"], 0) + 1
    imports = import_counts(root)
    files = len(mr.corpus_files(root))
    kinds = ", ".join(f"{k.lower().replace('_', ' ')} {v}" for k, v in sorted(by_class.items()))
    return "\n".join([
        README_BEGIN,
        "**The answer key at a glance** (generated by the verifier's write command; `verify_manifest.py` "
        "fails if any number here drifts)",
        "",
        f"- Specimens in the answer key: **{len(statuses)}** ({kinds}).",
        f"- **{levels[EXECUTION]}** are `VERIFIED_BY_EXECUTION`: the verifier ran the specimen in a sandbox and "
        "asserted the behaviour the verdict names.",
        f"- **{levels[STATIC]}** are `VERIFIED_BY_STATIC_CHECK`: the verdict is a property of the file text and "
        "the verifier compared the text. Nothing was run.",
        f"- **{levels[UNVALIDATED]}** are `UNVALIDATED`: the verdict rests on a human judgement or an outside "
        "measurement the verifier does not repeat. Each entry in `registry.json` says why.",
        f"- Files under `specimens/` whose SHA-256 is recorded and checked: **{files}**.",
        f"- Specimen files that import numpy: **{imports['numpy']}**; matplotlib: **{imports['matplotlib']}**.",
        f"- Unfinished-work markers (the word TO-DO in capitals) in the specimens, manifest and code: "
        f"**{count_todo_markers(root)}**.",
        README_END])


# ------------------------------------------------------------------ reporting

def render_report(report: Report, root: Path, *, show_pass: bool = True) -> Tuple[str, bool]:
    verdicts = _verdicts()
    lines: List[str] = []
    for c in report.claims:
        if c.skipped:
            lines.append(f"  SKIP  {c.label}")
        elif show_pass or not c.ok:
            lines.append(f"  {'PASS' if c.ok else 'FAIL'}  {c.label}")
    failures = report.failures
    total = [c for c in report.claims if not c.skipped]
    passed = len(total) - len(failures)
    lines.append("")
    lines.append(f"{passed}/{len(total)} manifest claims hold")
    if report.skips:
        lines.append(f"{len(report.skips)} claim(s) could not be run on this machine (missing library): "
                     + ", ".join(c.id for c in report.skips)
                     + ". Their entries keep the status already recorded in registry.json. "
                       "Install numpy and matplotlib, or run with --strict, to prove them here.")
    if failures:
        lines.append("")
        lines.append("MANIFEST DRIFT -- the answer key no longer matches the corpus.")
        lines.append("A specimen that was 'fixed' is a specimen destroyed; check whether")
        lines.append("the repair was intended before updating MANIFEST.md to match.")
        lines.append("")
        lines.append("WHAT FAILED, WHAT IT MEANS, AND WHAT TO DO")
        for c in failures:
            lines.append("")
            lines.append(f"* {c.label}")
            if c.reason:
                lines.append(f"    Reason: {c.reason}")
            if c.problem:
                lines.append(f"    What happened: {c.problem}")
            names = [f"{e} (verdict {verdicts.get(e, '?')})" for e in dict.fromkeys(c.unprovable)]
            if c.consequence:
                lines.append(f"    What it means: {c.consequence}")
            elif names:
                lines.append("    Verdicts that can no longer be trusted until this is resolved: "
                             + ", ".join(names[:12]) + (f", and {len(names) - 12} more" if len(names) > 12 else ""))
            lines.append(f"    What to do: {c.next_step}")
        return "\n".join(lines), False
    return "\n".join(lines) + "\nThe corpus matches its answer key.", True


# ------------------------------------------------------------------ commands

def run_all(root: Path, *, strict: bool = False) -> Report:
    return Verifier(root, strict=strict).all()


SUMMARY_PREFIX = "ASSAY-SUMMARY: "
SUMMARY_SCHEMA = "assay-summary/1"


def summary_record(report: Report, status: str = "") -> dict:
    """The machine-readable summary printed on one line (see README, 'The summary line')."""
    counts = _count_levels(report.derived) if report.derived else {EXECUTION: 0, STATIC: 0, UNVALIDATED: 0}
    total = [c for c in report.claims if not c.skipped]
    failures = report.failures
    return {
        "schema": SUMMARY_SCHEMA,
        "all_claims_hold": bool(report.claims) and not failures and not report.skips,
        "status": status or ("MANIFEST_INCONSISTENT" if failures else "UNKNOWN"),
        "claims": {"total": len(total), "passed": len(total) - len(failures), "failed": len(failures),
                   "skipped": len(report.skips)},
        "entries": {"total": len(report.derived), "counts": counts,
                    "status": {sid: st["validation"]["level"] for sid, st in sorted(report.derived.items())}},
        "failures": [{"claim": c.id, "reason": c.reason or "claim_failed", "detail": c.problem[:400]}
                     for c in failures],
    }


def failure_line(report: Report) -> str:
    """One stderr line saying why the key is not proven: which claim, and which reason."""
    total = [c for c in report.claims if not c.skipped]
    failures = report.failures
    head = f"ASSAY: answer key NOT PROVEN ({len(total) - len(failures)}/{len(total)} claims hold)."
    parts = []
    for c in failures[:3]:
        detail = " ".join((c.problem or c.label).split())
        parts.append(f"claim {c.id} failed because {c.reason or 'claim_failed'}: {detail[:220]}")
    more = f" (+{len(failures) - 3} more failing claim(s); see the report on stdout)" if len(failures) > 3 else ""
    return head + " " + " | ".join(parts) + more


def reexec_with_minimal_environment(root: Path, argv: Sequence[str]) -> None:
    """Restart the verifier with a minimal environment, so no secret of the caller is in its /proc/<pid>/environ.

    Only when this process is the real ``verify_manifest.py`` (never when
    imported by a test). If the restart is impossible, the secrets are at
    least removed from ``os.environ`` so nothing this process starts inherits them.
    """
    if os.environ.get("ASSAY_MINIMAL_ENV") == "1":
        return
    env = sandbox_module.minimal_parent_environment()
    script = Path(sys.argv[0]).resolve() if sys.argv and sys.argv[0] else None
    if script is not None and script == (Path(root) / "verify_manifest.py").resolve():
        try:
            sys.stdout.flush()
            sys.stderr.flush()
            os.execve(sys.executable, [sys.executable, str(script), *argv], env)
        except OSError:
            pass
    os.environ.clear()
    os.environ.update(env)


def main(root: Path, argv: Sequence[str]) -> int:
    strict = "--strict" in argv or bool(os.environ.get("ASSAY_STRICT"))
    if "--write" in argv:
        return write_all(root)
    reexec_with_minimal_environment(root, argv)
    sandbox_module.protect_current_process()
    sandbox_module.install_signal_cleanup()
    try:
        return _verify(root, strict)
    except Exception as exc:  # noqa: BLE001 - say why, then fail closed
        import traceback
        traceback.print_exc()
        print(f"ASSAY: answer key NOT PROVEN: the verifier itself failed ({type(exc).__name__}: {exc})",
              file=sys.stderr)
        return 1
    finally:
        sandbox_module.cleanup_active()


def _verify(root: Path, strict: bool) -> int:
    report = run_all(root, strict=strict)
    print("sandbox: " + describe_isolation())
    text, ok = render_report(report, root)
    print(text)
    verifier = ManifestVerifier(root)
    status = ""
    if report.derived:
        result = verifier.result_from_statuses(report.derived)
        result = verifier.mark_validated(result, [sid for sid, st in report.derived.items()
                                                  if st["validation"]["level"] != UNVALIDATED])
        status = result.status
        counts = _count_levels(report.derived)
        print(f"answer key status: {result.status} "
              f"({counts[EXECUTION]} verified by execution, {counts[STATIC]} by static check, "
              f"{counts[UNVALIDATED]} unvalidated, of {len(report.derived)} entries)")
    if not ok:
        status = "MANIFEST_INCONSISTENT"
    print(SUMMARY_PREFIX + json.dumps(summary_record(report, status), sort_keys=True, separators=(",", ":")))
    if not ok:
        print(failure_line(report), file=sys.stderr)
    if strict and report.skips:
        print("--strict: claims that could not be run count as failures.")
        print("ASSAY: --strict: " + str(len(report.skips)) + " claim(s) could not be run here (missing_dependency): "
              + ", ".join(c.id for c in report.skips), file=sys.stderr)
        return 1
    return 0 if ok else 1


def _count_levels(statuses: Dict[str, dict]) -> Dict[str, int]:
    out = {EXECUTION: 0, STATIC: 0, UNVALIDATED: 0}
    for st in statuses.values():
        out[st["validation"]["level"]] += 1
    return out


def write_all(root: Path) -> int:
    """Re-record the machine block, hashes, statuses and README block, after proving the corpus."""
    root = Path(root)
    report = run_all(root, strict=True)
    blocking = [c for c in report.claims if (not c.ok) and not c.regen]
    if blocking:
        text, _ = render_report(Report(claims=blocking), root, show_pass=False)
        print("refusing to write: the corpus does not behave as the claims say, so recording hashes now would")
        print("bless a damaged answer key. Fix these first (a deliberate change to a claim is a reviewed code")
        print("change, not something --write can do for you):")
        print(text)
        return 1
    # Statuses come from this run; entries whose claims were skipped are treated as blocking above.
    block = mr.build_block(root)
    block_text = mr.block_to_text(block)
    manifest_path = root / "MANIFEST.md"
    manifest_path.write_text(mr.replace_block(manifest_path.read_text(encoding="utf-8"), block_text),
                             encoding="utf-8", newline="\n")
    statuses = report.derived
    text = mr.render(root, block, statuses)
    written = json.loads(text)
    expected_count = len({s["id"] for s in mr.MANIFEST_SPECIMENS})
    if len(written) != len(mr.MANIFEST_SPECIMENS) or len(written) != expected_count:
        print(f"refusing to write: the table has {len(mr.MANIFEST_SPECIMENS)} rows but only {len(written)} "
              "distinct entries would be published.")
        return 1
    mr.registry_path(root).write_text(text, encoding="utf-8")
    readme = root / "README.md"
    rtext = readme.read_text(encoding="utf-8")
    m = _README_BEGIN_RE.search(rtext)
    if m and README_END in rtext:
        rtext = rtext[:m.start()] + readme_block(root, statuses) + rtext[rtext.index(README_END) + len(README_END):]
        readme.write_text(rtext, encoding="utf-8", newline="\n")
    else:
        print("README.md has no ASSAY-STATUS block; add the two marker lines where the status should appear.")
        return 1
    # Prove what was just written.
    check = run_all(root, strict=True)
    if check.failures:
        out, _ = render_report(Report(claims=check.failures), root, show_pass=False)
        print("wrote files, but the verifier does not accept them:")
        print(out)
        return 1
    counts = _count_levels(statuses)
    on_disk, _ = mr.load_registry_strict(mr.registry_path(root))
    print(f"wrote assay_production/registry.json: {len(on_disk)} specimens in the file, "
          f"{len(mr.MANIFEST_SPECIMENS)} rows in the table")
    print(f"recorded SHA-256 for {len(block['corpus_files'])} files under specimens/ and for the MANIFEST.md block")
    print(f"validation: {counts[EXECUTION]} verified by execution, {counts[STATIC]} by static check, "
          f"{counts[UNVALIDATED]} unvalidated")
    return 0
